name: lint & test

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # pull_request:
  #   branches: [main]
  push:
    branches: [release]
    paths:
      - "scripts/**"
      - "rootmoi/**"
      - ".github/workflows/lint_and_test.yaml"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        variant: [devcontainer, gnome]
        os: [ubuntu-22.04, ubuntu-20.04]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          scripts/test_for_ci.sh --variant "${{ matrix.variant }}" --os "${{ matrix.os }}"
